### ISSUE TITLE
Redirect alle urler til å ende med /

### ISSUE THREAD

**Issue by torenord** [radikalportal/radikalportal#11]
Redirect for å få en kanonisk url på alle sider:
- Fra: http://radikalportal.no/2015/09/24/fabian-stang-moxnes-dommen-kan-gjore-begrensning-av-bystyrets-innsynsrett-nodvendig
- Til: http://radikalportal.no/2015/09/24/fabian-stang-moxnes-dommen-kan-gjore-begrensning-av-bystyrets-innsynsrett-nodvendig/

**Comment by kjella** [comment]
Mulig denne er løst, eller at jeg misforstår feilen.
Uansett vil jeg påstå at en "unik" eller en "cannonical" url til et unikt innholdsobjekt er å foretrekke.

Når jeg undersøker i dag, er dette det jeg opplever...
- Jeg går til følgende URL som gir en 301 redirect response:
  - http://radikalportal.no/2015/09/24/fabian-stang-moxnes-dommen-kan-gjore-begrensning-av-bystyrets-innsynsrett-nodvendig
- Headeren som blir sendt til klienten er:
  - Location:"http://radikalportal.no/2015/09/24/fabian-stang-moxnes-dommen-kan-gjore-begrensning-av-bystyrets-innsynsrett-nodvendig/"

Dette er etter alt å dømme riktig oppførsel?

**Comment by torenord** [comment]
Dette er rart. Jeg får også 301 med curl. Men både Firefox og Chrome laster inn siden uten å legge til / i adressefeltet.

Grunnen til at dette var et problem var at lenken til saken ble postet på Facebook uten / og det førte til at alle likes-ene gikk til siden uten /. Men av en eller annen grunn har Facebook nå merget likes-ene, så begge urlene har samme antall likes.

Jeg tenker at vi kan stenge dette issuet for nå og heller komme tilbake til det hvis Facebook får problemer igjen.
