### ISSUE TITLE
Oppdateringer av wordpress "utvidelser" lar seg ikke installere

### ISSUE THREAD

**Issue by kjella** [radikalportal/radikalportal#12]
Jeg får beskjed om at wordpress ikke har tilstrekkelige rettigheter til å opprette katalog(er).

**Comment by torenord** [comment]
Greia er at vi har hele wordpressinstallasjonen i gitrepoet slik at hvis vi pusher commiter til serveren vil plugins som har blitt oppdatert gjennom brukergrensesnittet bli overskrevet.

**Comment by kjella** [comment]
En mulig løsning, er jo å laste ned og kjøre opp Wordpress lokalt.
Da kan man sette igang de nødvendige oppdateringene og commite disse til github repoet.
Dette er muligens noe "tryggere" enn å laste ned utvidelsene direkte i produksjon også commite rett til master branchen.

**Comment by torenord** [comment]
Skjønte ikke helt hva du mente i den siste setningen. Men jeg tror det er det vi har gjort til nå.

Når ting skal oppdateres, plugins eller wordpress, så laster jeg det ned til min lokale versjon av nettsiden. Installerer og tester at oppdateringene ikke skaper noen problemer. Så committer jeg og pusher til serveren. Så går jeg på serveren og purger cachene og tester at ting ser OK.

**Comment by kjella** [comment]
Ok, det høres veldig fornuftig ut.
Bruker du da en "ren" database eller en dump av produksjonsdatabasen?
Vi burde hatt mulighet til å hente ut en kopi av produksjonsdatabasen for å kjøre lokalt, men med nødvendig anonymisering

**Comment by torenord** [comment]
Dump av produksjonsdatabasen. Ja, jeg har gjort det tidligere, men da har jeg gjort det manuelt (overskrev alle passordhashene jeg fant i mysql). Vi burde hatt et skript som gjorde dette automatisk (opprettet #14).
