### ISSUE TITLE
Facebook like-dialog kuttes i artikler

### ISSUE THREAD

**Issue by torenord** [radikalportal/radikalportal#15]
Når man klikker på Facebook-knappen "Liker" i en artikkel popper det ut en dialogboks, men den kuttes. Se bildet.

<img width="574" alt="skjermbilde 2015-10-01 kl 11 43 59" src="https://cloud.githubusercontent.com/assets/395169/10217712/e7f8655c-6831-11e5-92e9-b3c6a1a45684.png">

**Comment by vegardvelle** [comment]
Dette er ikke fikset. Samme problem fremdeles i dag
![liker-kutt](https://cloud.githubusercontent.com/assets/14995818/10360317/142a84de-6da0-11e5-875b-69db7c818fd0.JPG)

**Comment by vegardvelle** [comment]
Jeg bruker Google Chrome.

**Comment by torenord** [comment]
Det bør være fikset nå.

**Comment by vegardvelle** [comment]
Ikke fikset. I dag hadde jeg samme problem.

**Comment by torenord** [comment]
Skjønner ikke hvorfor det ikke har fungert tidligere. Jeg sjekket og dobbeltsjekket. Forhåpentligvis fungerer det denne gangen.
