### ISSUE TITLE
Boks for anbefalte videoer på forsiden

### ISSUE THREAD

**Issue by vegardvelle** [radikalportal/radikalportal#18]
Vi har lenge snakket om å få opp en boks på siden hvor vi kan legge inn videoer vi anbefaler, for eksempel fem synlige anbefalinger om gangen. Og slik at den nyeste anbefalingen skyver ut av synlighet den eldste ved publisering. Det enkleste er vel om lenken til videoen tar deg til siden hvor videoen først er lagt ut. Men det kunne være fint om det lå en samlet oversikt med slike anbefalte videoer på sidene våre.

**Comment by abdgun** [comment]
De ble lagt inn som Eksternt innhold i wordpress og har eksternt-innhold som slug. Er det bedre å kalle dem anbefalinger i stedet?

**Comment by torenord** [comment]
Det er kanskje det. Eller "eksterne-anbefalinger" kanskje? Det er ikke så fryktelig viktig hvis det bare er synlig internt, men å få med ordet "anbefaling" vil kanskje gi mer mening.
