### ISSUE TITLE
Google news

### ISSUE THREAD

**Issue by vegardvelle** [radikalportal/radikalportal#21]
Hva skal til for at vi kan få spredd sakene våre via Google news? Kan vi gjøre det?

**Comment by kjella** [comment]
Kjenner ikke til denne. Fant heller ikke noe dokumentasjon som tilsier at dette er mulig.
Dog er det mulig at de bruker openGraph og om vi benytter dette for å beskrive våre artikler, vil sannsynligheten øke for at de publiserer våre nyheter.

**Comment by vegardvelle** [comment]
Kristian Jørgensen kjenner til dette best. Skal be han hekte seg på denne lenken.

**Comment by kjella** [comment]
En Google konto som skal administrere relasjonen mellom Google News og radikalportal må benyttes her: 
https://partnerdash.google.com/partnerdash/d/news#p:id=pfehome
