### ISSUE TITLE
H1, hva er den

### ISSUE THREAD

**Issue by vegardvelle** [radikalportal/radikalportal#24]
Det virker litt uklart hvordan vi definerer RP i H1, altså den grunnleggende informasjonen om hva RP er for noe. På vedlagte bilde er førsteplassen korrekt. Slik skal det være. Men hva er femte, og spesielt sjuendeplassen for noe? I hvert fall sjuendeplassen burde ikke finnes.
![h1 pa rp](https://cloud.githubusercontent.com/assets/14995818/10362136/fd43a040-6dac-11e5-94f1-dc9c21e044eb.jpg)

**Comment by torenord** [comment]
Hva er H1? Hvor (og når) er dette bildet fra? Ser at det er fra Google Analytics, og ikke tatt nylig. Jeg har endret tittel på forsiden nå, så 7 og og 1 (som begge refererer til forsiden) blir samme linje. 5 er sannsynligvis forsiden, men er ikke sikker. Kunne lett funnet det ut hvis jeg så det selv på Google Analytics.

**Comment by vegardvelle** [comment]
Mulig H1 ikke er det rette begrepet. Det jeg mener er metabeskrivelsen som definerer siden. Denne er synlig for Google og folk som googler oss.
