### ISSUE TITLE
Twitter-tull

### ISSUE THREAD

**Issue by vegardvelle** [radikalportal/radikalportal#25]
De siste par ukene har jeg hatt problemer med å twitre saker fra siden vår når Twitter-appen har vært åpen på telefonen. Når jeg trykker på twitter-knappen øverst i artikkelen, kommer jeg bare til en blank side i stedet for å få opp en ferdig tweet, som jeg kan redigere eller trykke publiser på. Dette problemer virker ikke som det er til stede når twitter-appen ikke er åpen, men det er den jo som regel hos meg (og sikkert mange andre). NB: iPhone

**Comment by vegardvelle** [comment]
Nå har også @radikalportal blitt borte fra Twitter-meldingene som du poster fra knappen på teksten. Det bør være med.

**Comment by torenord** [comment]
@vegardvelle: Kan du poste separate problemer i separate issues så blir det enklere å holde orden på?

Klarer ikke reprodusere det første problemet på min iPhone.
