### ISSUE TITLE
Aktuelt-header

### ISSUE THREAD

**Issue by vegardvelle** [radikalportal/radikalportal#27]
Aktuelt-headeren er blitt borte fra sidene våre. Det betyr at aktueltsakene vi lager ganske raskt (når de er vekke fra toppen) forsvinner inn i limbo. Det samme gjelder tidligere aktuelsaker vi har laget. Vi bør få en inngang til denne kategorien på forsiden. NB: haster litt.

**Comment by torenord** [comment]
Den er der fortsatt for meg.

**Comment by vegardvelle** [comment]
Ser den.  Sikkert bare jeg som overså det.
