### ISSUE TITLE
Sett opp https på wp-login.php

### ISSUE THREAD

**Issue by torenord** [radikalportal/radikalportal#6]
Eller enda bedre: Hele nettsiden.

**Comment by kjella** [comment]
Er det greit å benytte et "self-signed" sertifikat? Da blir det presentert som en advarsel og muligens "uttrygt" sertifikat. Dette kan ha den effekten at noen brukere blir litt skremt av det.

**Comment by torenord** [comment]
Vi bør ikke ha self-signed sertifikat, nei. Cloudflare har en feature hvor de kan aktivere https mellom dem og brukerne. Det vil hjelpe litt på sikkerheten. Men da jeg prøvde å sette det opp fikk jeg mange problemer med css og js som ikke ble lastet inn. Å løse denne krever å tukle endel med nginx-configen, så jeg assigner denne til meg selv foreløpig.

**Comment by torenord** [comment]
Fikset.
