### ISSUE TITLE
Forsideslider beveger innholdet under

### ISSUE THREAD

**Issue by torenord** [radikalportal/radikalportal#8]
Hvis det er et bilde eller video i slideren på forsiden som har et annet sideforhold enn det riktig (16:10), så blir alt innholdet flyttet opp eller ned når slideren kommer til dét bildet.

**Comment by kjella** [comment]
Har gått igjennom sidene nå og finner ikke et eksempel hvor dette skjer.
Skjer dette uansett hvilken responsive regelsett i CSS som blir benyttet?

**Comment by torenord** [comment]
Det er ikke alltid det er bilder i slideren som har feil sideforhold, men akkurat nå er det det. Se eksempelet under. Her er det første bildet 700 x 402 (sideforhold 1.74) og det andre 700 x 437 (sideforhold 1.6).

Ja, dette skjer i alle responsive regelsett.

Forskjellige løsninger er mulig. Det beste hadde vært å tvinge cropping av bilder ved å tvinge folk til å gjøre det i admingrensesnittet. Alternativt kunne vi hatt en php-funksjon som automatisk cropper bilder som blir publisert med feil sideforhold. Ulempen med det vil være at denne croppefunksjonen ikke alltid vil croppe bildene på en god måte (kan f.eks. kutte hodet på en person, det ville ikke vært bra). En siste mulighet er å gjøre det samme i CSSen, men det tror jeg vil være mye mer jobb.

![skjermbilde 2015-09-26 kl 13 32 25](https://cloud.githubusercontent.com/assets/395169/10117323/2c5dc846-6453-11e5-8db0-44cc35d3b432.png)
![skjermbilde 2015-09-26 kl 13 32 20](https://cloud.githubusercontent.com/assets/395169/10117324/2c6189cc-6453-11e5-93e9-0769393640f7.png)

**Comment by kjella** [comment]
Den enkleste løsningen er jo å sette en fast høyde på karusellen. Da oppnår vi at teksten på resten av siden ikke hopper opp og ned etterhvert som den bytter sak. 
Ref: https://github.com/radikalportal/radikalportal/issues/4

**Comment by torenord** [comment]
Enig i at dette er den enkleste løsningen, vi bør gjøre dette først. Har du lyst til å ta på deg denne?

**Comment by kjella** [comment]
Ja, det gjør jeg gjerne

**Comment by kjella** [comment]
Nå har vi et godt eksempel på hvor ille forsiden kan bli. Her holder det helt klart ikke med en mindre CSS justering. Jeg fant en wordpress plugin som vi kan vurdere å installere
https://wordpress.org/plugins/manual-image-crop/

![screenshot from 2015-10-02 10 10 36](https://cloud.githubusercontent.com/assets/144996/10242019/f1aac5d8-68ed-11e5-8ab1-56f61c0b321c.png)
